# Generated by Django 4.1 on 2022-08-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_remove_comment_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='ادرس آی پی')),
            ],
            options={
                'verbose_name': 'آدرس آی پی',
                'verbose_name_plural': 'آدرس های آی پی',
            },
        ),
        migrations.RemoveField(
            model_name='video',
            name='view',
        ),
        migrations.AddField(
            model_name='video',
            name='view',
            field=models.ManyToManyField(blank=True, related_name='view', to='videos.ipaddress', verbose_name='بازدید ها'),
        ),
    ]
