# Generated by Django 4.1 on 2022-08-31 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_ipaddress_remove_video_view_video_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like', to='videos.video', verbose_name='ویدیو'),
        ),
    ]
