# Generated by Django 4.1 on 2022-08-31 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_alter_like_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='videos.video', verbose_name='ویدیو'),
        ),
    ]
