# Generated by Django 4.1 on 2022-09-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_alter_video_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='send_email',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='ارسال به ایمیل'),
        ),
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, verbose_name='اسلاگ'),
        ),
    ]
