# Generated by Django 4.1 on 2022-08-23 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='پست الکترونیکی')),
                ('username', models.CharField(max_length=155, unique=True, verbose_name='نام کاربری')),
                ('full_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام کامل')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='شماره همراه')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar_user', verbose_name='عکس پروفایل')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(verbose_name='بیو')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='توییتر')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='لینکدین')),
                ('github', models.URLField(blank=True, null=True, verbose_name='گیت هاب')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='اینستاگرام')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_rel', to=settings.AUTH_USER_MODEL, verbose_name=' کاربر')),
            ],
            options={
                'verbose_name': 'معلم',
                'verbose_name_plural': 'معلمین',
            },
        ),
    ]
