# Generated by Django 4.1 on 2022-09-13 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_otpcode'),
        ('accounts', '0005_user_token'),
    ]

    operations = [
    ]
